services:
  web:
    build:
      context: ./docker
    container_name: tippspiel_web
    environment:
      BARKEEPER_PASSWORD: "changeme"
      ADMIN_PASSWORD: "changeme"
      CURRENT_TURNIER: "51"
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: tippspiel
      DB_USER: "${DB_USER:-webserver}"
      DB_PASSWORD: "${DB_PASSWORD:-changeme}"
    ports:
      - "50080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.11
    container_name: tippspiel_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-changeme}"
      MYSQL_DATABASE: tippspiel
      MYSQL_USER: "${DB_USER:-webserver}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-changeme}"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tippspiel_phpmyadmin
    ports:
      - "50081:80"
    environment:
      PMA_HOST: db
      PMA_USER: "${DB_USER:-webserver}"
      PMA_PASSWORD: "${DB_PASSWORD:-changeme}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-changeme}"
    depends_on:
      - db
    restart: unless-stopped

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: tippspiel_code-server
    profiles:
      - development
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
      DEFAULT_WORKSPACE: /var/www/html/
    volumes:
      - ./docker/csconfig:/config
      - ./:/var/www/html
    ports:
      - "50082:8443"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tippspiel_cloudflared
    profiles: 
      - "tunnel"
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mysqldata: